name: ci-cd

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: bash scripts/setup.sh

    - name: Type check (mypy)
      run: mypy src/python/excalidraw_svg_to_lib --strict

    - name: Lint
      run: bash scripts/lint.sh

    - name: Test
      run: bash scripts/test.sh