name: ci-cd

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Install dependencies
      run: bash scripts/setup.sh

    - name: Lint
      run: bash scripts/lint.sh

    - name: Test
      run: bash scripts/test.sh